root_dir: '/app/data/books' # path_to_your_root_directory
databases_dir: '/app/src/backend/databases/vectordb' # path_to_your_databases_directory
grades:
  - Grade4
  - Grade5
embedding_model:
  name: sentence-transformers/all-MiniLM-L6-v2
  chunk_size: 256
  chunk_overlap: 25
query_config:
  top_k: 3
  similarity_cutoff: 0.3